# .travis.yml for Moodle theme_morecandy:byLazyDaisy

language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0

matrix:
 allow_failures:
  - php: 7.0

env:
 global:
  - MOODLE_BRANCH=master
  # - IGNORE_PATHS=amd/build,amd/src/affix.js,amd/src/bootstrap.js,amd/src/carousel.js,amd/src/fitvids.js,amd/src/jBreadCrumb.js
  # Ignore custom.css until CSSlint can be instructed to ignore lines for '[[setting:customcss]]'.
  # Also ignore generated CSS files.
  - IGNORE_NAMES=*.txt,custom.css,sideway-header.css,settings.css,font-awesome.css,glyphicon-font.css,
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit


